#!/bin/bash

# This script needs to be run as root
echo "Checking if the script is run as root."
if [[ $EUID -ne 0 ]]; then
    echo -e "This script should be run as root. \n"
    exit
else
    echo -e "This script is run as root. Good to go. \n"
fi

# Checking if IPsec is installed
echo "Checking if IPsec is installed"
ipdir="/etc/ipsec.d"
if [ ! -d "$ipdir" ]; then
    echo "Directory /etc/ipsec.d DOES NOT exists. Please install IPsec (https://libreswan.org)"
    echo "For Fedora - dnf -y install libreswan-3.*"
    echo "For Centos - yum -y install libreswan-3.*"
    echo "For Ubuntu - apt-get -y install libreswan"
    exit
else
    echo -e "IPsec is installed. \n"
fi

# Copy the custom configuration in config/custom/ directory
read -p "Copy the custom certificates PKCS#12(.p12) in 'certs/custom/' directory and Type (yY): " confCopied

if [ "$confCopied" = "y" ] || [ "$confCopied" = "Y" ]; then
    for file in config/custom/*; do
        file=${file##*/}
        configFile=config/custom/"$file"
        cp "$configFile" "$ipdir"
        echo -e "\nNote - Make sure there is only one '.conf' file in the $ipdir , Listing contents of $ipdir\n"
        ls "$ipdir"
    done
else
    echo -e "\nNo custom config file found. \n"
fi
