#!/bin/bash

# This script needs to be run as root
echo "Checking if the script is run as root."
if [[ $EUID -ne 0 ]]; then
    echo -e "This script should be run as root. \n"
    exit
else
    echo -e "This script is run as root. Good to go. \n"
fi

# Checking if IPsec is installed
echo "Checking if IPsec is installed"
ipdir="/etc/ipsec.d"
if [ ! -d "$ipdir" ]; then
    echo "Directory /etc/ipsec.d DOES NOT exists. Please install IPsec (https://libreswan.org)"
    echo "For Fedora - dnf -y install libreswan-3.*"
    echo "For Centos - yum -y install libreswan-3.*"
    echo "For Ubuntu - apt-get -y install libreswan"
    exit
else
    echo -e "IPsec is installed. \n"
fi

# Copy the custom certificates in certs/custom/ directory
read -p "Copy the custom certificates PKCS#12(.p12) in 'certs/custom/' directory and Type (yY): " copied

if [ "$copied" = "y" ] || [ "$copied" = "Y" ]; then
    # Checking if nss database exists
    echo "Checking if nss database exists"
    dbFileCount=$(ls "$ipdir"/*.db 2>/dev/null | wc -l)
    if [ $dbFileCount != 0 ]; then
        echo -e "nss database exists. \n"
    else
        # Initializing the nss database
        echo "nss database does not exist. Initializing the nss database"
        ipsec initnss
    fi
    # Initializing the nss database
    echo "Initializing the nss database"
    ipsec initnss

    # Import certificate
    echo "Importing the selected PKCS#12(.p12) certificate from 'certs/custom/' into NSS Database"
    for file in certs/custom/*; do
        file=${file##*/}
        # Removing the file extension (.p12) from certificate
        name=${file%.p12}
        pk12util -d sql:/etc/ipsec.d -n "$name" -i certs/custom/"$file"
    done
fi
