#!/bin/bash

# This script needs to be run as root

# Checking if IPsec is installed
echo "Checking if IPsec is installed"
ipdir="/etc/ipsec.d"
if [ ! -d "$ipdir" ] 
then
	echo "Directory /etc/ipsec.d DOES NOT exists. Please install IPsec (https://libreswan.org)"
else
	echo "IPsec is installed."
fi


# Downloading the letsencrypt certificates
echo "Downloading the letsencrypt certificates"
DIR1="certs/CA"
# CA certificates
CERT1="https://letsencrypt.org/certs/isrgrootx1.pem.txt"
CERT2="https://letsencrypt.org/certs/trustid-x3-root.pem.txt"

DIR2="certs/intermediate"
# Intermediate certificates
CERT3="https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt"
CERT4="https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt"

# Downloading the CA certificates
wget_output=$(wget -P "$DIR1" "$CERT1" "$CERT2")
if [ $? -ne 0 ]; 
then
	echo "Certificates NOT FOUND." 
else
	echo "CA Certificates downloaded."
fi

# Downloading the Intermediate certificates
wget_output=$(wget -P "$DIR2" "$CERT3" "$CERT4")
if [ $? -ne 0 ]; 
then
	echo "Certificates NOT FOUND." 
else
	echo "Intermediate Certificates downloaded."
fi


# Importing the CA certificates
echo "Importing the downloaded certificates into NSS Database"
for file in certs/CA/*; do
  file=${file##*/}
  # Removing the file extension (.pem.txt) from certificates
  name=${file%.pem.txt}
  certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/CA/"$file" -t "CT,,"
done
echo "CA certificates Imported successfully."

# Importing the Intermediate certificates
for file in certs/intermediate/*; do
  file=${file##*/}
  # Removing the file extension (.pem.txt) from certificates
  name=${file%.pem.txt}
  certutil -A -d sql:/etc/ipsec.d -n "$name" -i certs/intermediate/"$file" -t "u,u,u"
done
echo "Intermediate certificates Imported successfully."
