#!/bin/bash

# This script needs to be run as root
echo "Checking if the script is run as root."
if [[ $EUID -ne 0 ]]; then
    echo -e "This script should be run as root. \n"
    exit
else
    echo -e "This script is run as root. Good to go. \n"
fi

# Updating the certificate using Certbot keeping the private key same
echo -e "Checking if Certbot is installed. \n"
certBotInstalled=$(command -v certbot)
if [ -z "$certBotInstalled" ]; then
    echo -e "Certbot not installed. \n"
    exit
else
    echo -e "Certbot is installed, Good to go. \n"
fi

echo -e "Updating the certificate using Certbot keeping the private key same. \n"
certbot renew --reuse-key

# Did your certificate update?
read -p "Did your certificate update? (yY/nN) " updateAnswer
if [ "$updateAnswer" = "n" ] || [ "$updateAnswer" = "N" ]; then
    exit
else
    # Importing the updated certificate in the nss database
    echo -e "Importing the updated certificate in the nss database"
    # Generating #pkcs12 file
    echo -e "Generating the #pkcs12 (.p12) file."
    echo -e "Downloading the required Intermediate certificate."

    # Downloading the required Intermediate certificate
    DIR=$(mktemp -d)
    CERT="https://letsencrypt.org/certs/letsencryptauthorityx3.pem.txt"

    wget_output=$(wget -q -P "$DIR" "$CERT")
    if [ $? -ne 0 ]; then
        echo "Certificates NOT Found OR Saving the certificate in directory failed"
        exit
    else
        echo -e "Intermediate Certificate downloaded in $DIR \n"
    fi

    # Renaming the certificates
    echo -e "Renaming the certificate."
    for file in "$DIR"/*; do
        file=${file##*/}
        # Removing the file extension (.txt) from certificates
        name=${file%.txt}
        mv "$DIR"/"$file" "$DIR"/"$name"
        echo -e "Certificate $DIR/$file renamed to $DIR/$name."
    done

    # Now generating the #pkcs12 (.p12) file
    read -p "Enter the cert directory location (e.g. /etc/letsencrypt/live/letsencrypt.libreswan.org): " LetsEncryptCertDir

    openssl pkcs12 -export -inkey "$LetsEncryptCertDir"/privkey.pem -in "$LetsEncryptCertDir"/fullchain.pem -CAfile "$DIR"/"$name" -out "$LetsEncryptCertDir"/generatedCertificate.p12

    # Importing the certificate in nss database
    echo -e "\nImporting the certificate in nss database."
    pk12util -d sql:/etc/ipsec.d -i "$LetsEncryptCertDir"/generatedCertificate.p12

    # Displaying the certificates installed in nss database
    echo -e "Displaying the certificates installed in nss database. \n"
    certutil -L -d sql:/etc/ipsec.d

    # To confirm the success try running the test connection script on the client
    echo -e "\nTo confirm the success try running the test connection script on the client"
fi
